title: Estadística y Ciencia de Datos
email: aloctavodia@gmail.ocm
description: Curso introducctorio de ciencia de datos y estadística bajo Python
theme: jekyll-theme-cayman
source: https://github.com/aloctavodia/intro_ciencia_de_datos/archive/master.zip
